# Testing linked worklfows...this should not make itself to main
name: Workflow 1
on:
  push:
    branches:
      - "main"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Hello, World? \U0001F937\""
